version: "3"

services:
  vault-dev:
    image: vault
    container_name: vault-dev
    command: vault server -config /vault/config/local.json
    cap_add:
      - IPC_LOCK
    volumes:
      - ../../secret-vault-dev/Vaultfile:/vault/backend_file:rw
    environment:
      - 'VAULT_API_ADDR=http://0.0.0.0:8200'
      - 'VAULT_ADDR=http://127.0.0.1:8200'
      - 'VAULT_LOCAL_CONFIG={"backend": { "file": { "path": "/vault/backend_file" } }, "default_lease_ttl": "168h", "max_lease_ttl": "720h", "listener": [{"tcp": {"address": "0.0.0.0:8200","tls_disable": 1}}]}'
    ports:
      - 127.0.0.1:8200:8200