version: "3"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  frontend: #ยง< data.config.hub.docker.services.frontend.name + ':'
    build:
      args:
        #ยง 'wise_sql_endpoint_url: "' + data.config.sql.url.staging + '"'
        wise_sql_endpoint_url: "https://sql.dev.wise.jblew.pl/"
    expose:
      - "8090"
    networks:
      - proxy-tier
    environment:
      #ยง 'VIRTUAL_HOST: "' + url(data.config.hub.url.staging).hostname + '"'
      VIRTUAL_HOST: "hub.dev.wise.jblew.pl"
      VIRTUAL_NETWORK: "caddy-proxy"
      VIRTUAL_PORT: 8090
      #ยง 'CADDY_TLS: ' + ( url(data.config.hub.url.staging).protocol === "https:" ? '"yes"' : '"no"')
      CADDY_TLS: "yes"
      CADDY_TIMEOUTS: "read 5m, write 2m"
    restart: always
