version: "3"

services:
  frontend: #ยง< data.config.hub.docker.services.frontend.name + ':'
    build:
      args:
        #ยง 'wise_sql_endpoint_url: "' + data.config.sql.url.production + '"'
        wise_sql_endpoint_url: "https://sql.wise.vote/"
    ports:
      - "8090:8090"