version: "3"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  frontend: #§< data.config.hub.docker.services.frontend.name + ':'
    container_name: wise-hub-frontend #§< 'container_name: ' + data.config.hub.docker.services.frontend.container
    build: ./wise-hub-frontend
    image: wise/wise-hub-frontend #§< 'image: ' + data.config.hub.docker.services.frontend.image
    expose:
      - "8090"
    networks:
      - proxy-tier
    environment:
      NODE_ENV: production
      #§ 'VIRTUAL_HOST: "' + data.config.hub.production.host + '"'
      VIRTUAL_HOST: "hub.wise.vote"
      VIRTUAL_NETWORK: "caddy-proxy"
      VIRTUAL_PORT: 8090
      #§ 'CADDY_TLS: ' + ( data.config.hub.production.schema === "https" ? '"yes"' : '"no"')
      CADDY_TLS: "yes"
      CADDY_TIMEOUTS: "read 5m, write 2m"

