version: "3"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  hub:
    container_name: wise-hub
    build: ./wise-hub-frontend
    expose:
      - "8080"
    networks:
      - proxy-tier
    environment:
      NODE_ENV: production
      #ยง 'VIRTUAL_HOST: "' + data.config.hub.production.host + '"'
      VIRTUAL_HOST: "hub.wise.vote"
      VIRTUAL_NETWORK: "caddy-proxy"
      VIRTUAL_PORT: 8080
      #ยง 'CADDY_TLS: ' + ( data.config.hub.production.schema === "https" ? '"yes"' : '"no"')
      CADDY_TLS: "yes"
      CADDY_TIMEOUTS: "read 5m, write 2m"

