version: "3.3"

services:
  #§ data.config.hub.docker.services.nginx.name + ':'
  nginx:
    image: nginx
    volumes:
      - ../nginx/site.template.conf:/etc/nginx/conf.d/mysite.template:ro
      - ..:/srv:ro
    environment:
      DOLLAR: '$$' #enables use of dollar sign in template.conf
    # for debug add: cat /etc/nginx/conf.d/default.conf &&
    command: /bin/bash -c "sleep 9 && envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  
  #§ data.config.hub.docker.services.redis.name + ':'
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    # expose: # this is stack, but leaving expose to give information on ports
    #   - 6379
    volumes:
      #§ '- ' + data.config.hub.docker.services.redis.volume + ':/data:rw'
      - wise_hub_redis:/data:rw

  #§ d(data.config.hub.docker.services.api.name) + ':'
  api:
    #§ 'image: ' + data.config.hub.docker.images.backend.name
    image: wise/hub-backend
    #command: sh -c "sleep 5 && node dist/api/index.js"
    command: ping 8.8.8.8
    # expose: # this is stack, but leaving expose to give information on ports
    #  - 3000
    environment:
      #§ 'REDIS_URL: redis://' + data.config.hub.docker.services.redis.name + ':6379/'
      REDIS_URL: redis://redis:6379/

  #§ d(data.config.hub.docker.services.daemon.name) + ':'
  daemon:
    #§ 'image: ' + data.config.hub.docker.images.backend.name
    image: wise/hub-backend
    command: sh -c "sleep 4 && node dist/daemon/index.js"
    environment:
      #§ 'REDIS_URL: redis://' + data.config.hub.docker.services.redis.name + ':6379/'
      REDIS_URL: redis://redis:6379/
      WISE_LOG_LEVEL: debug

  #§ d(data.config.hub.docker.services.publisher.name) + ':'
  publisher:
    #§ 'image: ' + data.config.hub.docker.images.backend.name
    image: wise/hub-backend
    command: sh -c "sleep 4 && node dist/publisher/index.js"
    environment:
      #§ 'REDIS_URL: redis://' + data.config.hub.docker.services.redis.name + ':6379/'
      REDIS_URL: redis://redis:6379/

  #§ d(data.config.hub.docker.services.realtime.name) + ':'
  realtime:
    #§ 'image: ' + data.config.hub.docker.images.backend.name
    image: wise/hub-backend
    command: sh -c "sleep 4 && node dist/realtime/index.js"
    ports:
      #§ '- ' + data.config.hub.docker.services.realtime.port + ':' + data.config.hub.docker.services.realtime.port
      - 8099:8099
    environment:
      #§ 'REDIS_URL: redis://' + data.config.hub.docker.services.redis.name + ':6379/'
      REDIS_URL: redis://redis:6379/


volumes:
  #§ data.config.hub.docker.services.redis.volume + ':'
  wise_hub_redis:

# TODO: do not forget about restart always on production